[project]
name = "lingua"
version = "0.0.0"
dependencies = [
    "ninja",
    "torch==2.5.0",
    "numpy",
    "omegaconf",
    "msgspec",
    "rouge-score",
    "sacrebleu",
    "sentencepiece",
    "tiktoken",
    "fsspec",
    "blobfile",
    "wandb",
    "viztracer",
    "lm-eval",
    "scipy",
    "pynvml",
    "datatrove",
    "orjson",
] 

[tool.uv.sources]
xformers = { index = "pytorch" }
torch = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
explicit = true